export type ListeningLevel = 'N5' | 'N4' | 'N3' | 'N2' | 'N1';

export type ListeningMondai = 'Mondai 1' | 'Mondai 2' | 'Mondai 3' | 'Mondai 4';

export interface ListeningSegment {
  speaker: string;
  text: string;
}

export interface ListeningPractice {
  id: string;
  level: ListeningLevel;
  mondai: ListeningMondai;
  title: string;
  summary: string;
  situation: string;
  durationSec: number;
  focus: string;
  question: string;
  options: string[];
  answer: string;
  explanation: string;
  audioUrl?: string | null;
  segments: ListeningSegment[];
}

export const LISTENING_LEVEL_META: Record<ListeningLevel, { badgeBg: string; badgeText: string; accent: string; desc: string }> = {
  N5: { badgeBg: '#DCFCE7', badgeText: '#15803D', accent: '#4ADE80', desc: 'Can ban, hoi thoai rat ngan' },
  N4: { badgeBg: '#DBEAFE', badgeText: '#1D4ED8', accent: '#60A5FA', desc: 'Hoi thoai thong dung' },
  N3: { badgeBg: '#FEF9C3', badgeText: '#92400E', accent: '#FACC15', desc: 'Tinh huong mo rong' },
  N2: { badgeBg: '#FFEDD5', badgeText: '#C2410C', accent: '#FB923C', desc: 'Nghe cong viec, thong bao' },
  N1: { badgeBg: '#FFE4E6', badgeText: '#BE123C', accent: '#FB7185', desc: 'Noi dung hoc thuat, phan tich' },
};

export const LISTENING_MONDAI_LABELS: Record<ListeningMondai, string> = {
  'Mondai 1': 'Chon y dung trong hoi thoai ngan',
  'Mondai 2': 'Nhip hoi dap va chon hanh dong',
  'Mondai 3': 'Nghe thong bao va tim thong tin',
  'Mondai 4': 'Nghe noi dung dai hon va tong hop y',
};

export const LISTENING_PRACTICES: ListeningPractice[] = [
  {
    id: 'n5-m1-combini',
    level: 'N5',
    mondai: 'Mondai 1',
    title: 'Mua do an o combini',
    summary: 'Hoi thoai ngan ve viec chon mon an truoc gio hoc.',
    situation: 'Ban be hen nhau mua do an o cua hang tien loi.',
    durationSec: 36,
    focus: 'Gia tien, lua chon don gian',
    question: 'Hai nguoi se mua gi?',
    options: ['Banh mi va sua', 'Onigiri va tra', 'Mi goi va nuoc', 'Banh ngot va ca phe'],
    answer: 'Onigiri va tra',
    explanation: 'Nguoi nam noi se lay onigiri, nguoi nu noi lay them mot chai tra.',
    segments: [
      { speaker: 'A', text: 'もうすぐ 授業ですね。コンビニで 何か 買いましょうか。' },
      { speaker: 'B', text: 'そうですね。わたし、おにぎりを 一つ 買います。' },
      { speaker: 'A', text: 'じゃあ、ぼくは お茶を 二本 買います。' },
      { speaker: 'B', text: '一本で いいです。いっしょに 飲みましょう。' },
    ],
  },
  {
    id: 'n5-m2-station',
    level: 'N5',
    mondai: 'Mondai 2',
    title: 'Hen gap o nha ga',
    summary: 'Nghe thoi gian va dia diem gap mat.',
    situation: 'Mot nguoi goi dien thay doi diem hen.',
    durationSec: 41,
    focus: 'Gio giac, dia diem',
    question: 'Hai nguoi se gap nhau o dau?',
    options: ['Cua Tay', 'Cua Dong', 'Truoc cua hang sach', 'Ben tram xe buyt'],
    answer: 'Cua Dong',
    explanation: 'Ban dau hen o cua Tay nhung sau do doi sang cua Dong.',
    segments: [
      { speaker: 'A', text: 'もしもし、六時に 駅の 西口で 会いますね。' },
      { speaker: 'B', text: 'すみません、西口は 工事中です。東口に しても いいですか。' },
      { speaker: 'A', text: 'わかりました。じゃあ、東口の パン屋の 前で。' },
      { speaker: 'B', text: 'はい、六時に 行きます。' },
    ],
  },
  {
    id: 'n5-m3-train-delay',
    level: 'N5',
    mondai: 'Mondai 3',
    title: 'Thong bao tau den cham',
    summary: 'Nghe thong bao ngan tai nha ga.',
    situation: 'Thong bao cong cong.',
    durationSec: 28,
    focus: 'Thong tin giao thong can ban',
    question: 'Tau di Ueno den cham bao lau?',
    options: ['5 phut', '10 phut', '15 phut', '20 phut'],
    answer: '10 phut',
    explanation: 'Thong bao noi tau den cham muoi phut do mua lon.',
    segments: [
      { speaker: 'Announcer', text: '上野行きの 電車は 大雨のため、十分ほど 遅れて います。' },
      { speaker: 'Announcer', text: 'ご利用の お客様は 三番線で お待ち ください。' },
    ],
  },
  {
    id: 'n4-m1-restaurant',
    level: 'N4',
    mondai: 'Mondai 1',
    title: 'Goi mon o quan an',
    summary: 'Hoi thoai ve mon chinh va nuoc uong.',
    situation: 'Khach va nhan vien goi mon.',
    durationSec: 45,
    focus: 'Mon an, thay doi don goi',
    question: 'Nguoi phu nu cuoi cung goi gi?',
    options: ['Ca ri va tra da', 'Miso ramen va nuoc', 'Udon va tra nong', 'Com ca va ca phe'],
    answer: 'Udon va tra nong',
    explanation: 'Co ay doi tu ramen sang udon va chon tra nong.',
    segments: [
      { speaker: 'Staff', text: 'ご注文は お決まりですか。' },
      { speaker: 'A', text: 'みそラーメンを お願いします。あ、やっぱり うどんに します。' },
      { speaker: 'Staff', text: '飲み物は いかがですか。' },
      { speaker: 'A', text: '冷たい水ではなくて、温かい お茶を ください。' },
    ],
  },
  {
    id: 'n4-m2-absence-call',
    level: 'N4',
    mondai: 'Mondai 2',
    title: 'Xin nghi buoi hoc',
    summary: 'Nghe ly do xin nghi va viec nop bai.',
    situation: 'Sinh vien goi cho giao vien.',
    durationSec: 52,
    focus: 'Ly do, cach xu ly tiep theo',
    question: 'Sinh vien phai lam gi?',
    options: ['Nop bai hom nay', 'Den lop chieu mai', 'Gui bai bang email', 'Gap co giao o van phong'],
    answer: 'Gui bai bang email',
    explanation: 'Co giao bao sinh vien gui bai tap qua email truoc toi nay.',
    segments: [
      { speaker: 'A', text: '先生、熱が あるので、今日の 授業を 休みます。' },
      { speaker: 'B', text: 'わかりました。宿題は できましたか。' },
      { speaker: 'A', text: 'はい、もう できました。' },
      { speaker: 'B', text: 'では、今晩までに メールで 送って ください。' },
    ],
  },
  {
    id: 'n4-m3-room-change',
    level: 'N4',
    mondai: 'Mondai 3',
    title: 'Doi phong hoc',
    summary: 'Thong bao thay doi phong hoc trong truong.',
    situation: 'Thong bao tai hanh lang truong.',
    durationSec: 31,
    focus: 'So phong, ly do thay doi',
    question: 'Lop chuyen sang phong nao?',
    options: ['Phong 201', 'Phong 305', 'Phong 501', 'Phong 510'],
    answer: 'Phong 305',
    explanation: 'Thong bao noi phong 201 dang sua may chieu nen lop hoc o phong 305.',
    segments: [
      { speaker: 'Announcer', text: '二〇一教室の プロジェクターが 故障したため、三時からの 授業は 三〇五教室で 行います。' },
      { speaker: 'Announcer', text: 'お間違えの ないように お願いします。' },
    ],
  },
  {
    id: 'n3-m1-meeting',
    level: 'N3',
    mondai: 'Mondai 1',
    title: 'Sap xep hop nhom',
    summary: 'Ba nguoi thong nhat lich hop cho du an.',
    situation: 'Trao doi trong cau lac bo.',
    durationSec: 66,
    focus: 'So sanh lua chon, tong hop lich',
    question: 'Nhom se hop luc nao?',
    options: ['Thu sau 6 gio', 'Thu bay 10 gio sang', 'Chu nhat 2 gio chieu', 'Thu bay 2 gio chieu'],
    answer: 'Thu bay 10 gio sang',
    explanation: 'Hai nguoi khong ranh chieu thu bay va chu nhat, nen chon sang thu bay.',
    segments: [
      { speaker: 'A', text: '今週、発表の 打ち合わせを したいですね。' },
      { speaker: 'B', text: '金曜日の 六時は アルバイトが あって 無理です。' },
      { speaker: 'C', text: '日曜日の 午後は 家族の 予定が あります。' },
      { speaker: 'A', text: 'じゃあ、土曜日の 午前十時なら どうですか。' },
      { speaker: 'B', text: 'それなら 大丈夫です。' },
      { speaker: 'C', text: 'わたしも 行けます。' },
    ],
  },
  {
    id: 'n3-m2-weekend-course',
    level: 'N3',
    mondai: 'Mondai 2',
    title: 'Chon khoa hoc cuoi tuan',
    summary: 'Nghe 2 lua chon khoa hoc va muc tieu hoc tap.',
    situation: 'Ban hoc vien hoi tu van vien.',
    durationSec: 59,
    focus: 'Muc tieu hoc tap, uu tien noi dung',
    question: 'Hoc vien nen chon khoa nao?',
    options: ['Khoa viet email', 'Khoa thuyet trinh', 'Khoa doc tin tuc', 'Khoa ngu phap nang cao'],
    answer: 'Khoa thuyet trinh',
    explanation: 'Hoc vien can cai thien ky nang noi truoc lop nen duoc khuyen khoa thuyet trinh.',
    segments: [
      { speaker: 'A', text: '週末の コースを 取りたいんですが、仕事で 発表する ことが 多いんです。' },
      { speaker: 'B', text: 'それなら、メール作文より プレゼンテーションの クラスが いいですね。' },
      { speaker: 'A', text: '人前で 話すのが 苦手なので、ぜひ 参加したいです。' },
      { speaker: 'B', text: '土曜日の 午後に 初級クラスが ありますよ。' },
    ],
  },
  {
    id: 'n3-m3-hall-announcement',
    level: 'N3',
    mondai: 'Mondai 3',
    title: 'Thong bao tai hoi truong',
    summary: 'Nghe huong dan vao cua va nhan tai lieu.',
    situation: 'Truoc su kien cong cong.',
    durationSec: 37,
    focus: 'Thu tu thao tac, dia diem nhan tai lieu',
    question: 'Nguoi tham du phai lam gi truoc khi vao hoi truong?',
    options: ['Mua ve moi', 'Nhan tai lieu o ban so 2', 'Ky ten o cua sau', 'Gui hanh ly o tang 2'],
    answer: 'Nhan tai lieu o ban so 2',
    explanation: 'Thong bao yeu cau nhan tai lieu o ban so 2 truoc khi vao.',
    segments: [
      { speaker: 'Announcer', text: '講演会に 参加される 方は、会場に 入る 前に 二番カウンターで 資料を 受け取って ください。' },
      { speaker: 'Announcer', text: 'その後、前の ドアから お入りください。' },
    ],
  },
  {
    id: 'n3-m4-library',
    level: 'N3',
    mondai: 'Mondai 4',
    title: 'Thu tuc muon sach thu vien',
    summary: 'Nghe huong dan co nhieu buoc.',
    situation: 'Nhan vien thu vien giai thich thu tuc moi.',
    durationSec: 71,
    focus: 'Nho thu tu buoc va dieu kien',
    question: 'Nguoi nghe phai lam gi neu chua co the thu vien?',
    options: ['Dang ky online truoc', 'Hoi ban tiep dan', 'Di chup anh the', 'Mua the tam thoi'],
    answer: 'Hoi ban tiep dan',
    explanation: 'Nhan vien noi neu chua co the thi den ban tiep dan de lam thu tuc.',
    segments: [
      { speaker: 'Staff', text: '本を 借りる 前に、学生証か 図書館カードを 機械に かざしてください。' },
      { speaker: 'Staff', text: 'カードを お持ちで ない 方は、先に 受付で 登録を してください。' },
      { speaker: 'Staff', text: '返却日は レシートに 書いて ありますので、確認を お願いします。' },
    ],
  },
  {
    id: 'n2-m1-client-call',
    level: 'N2',
    mondai: 'Mondai 1',
    title: 'Trao doi voi khach hang',
    summary: 'Nghe yeu cau dieu chinh lich giao hang.',
    situation: 'Nhan vien cong ty va khach hang dien dam.',
    durationSec: 74,
    focus: 'Thong tin cong viec, uu tien xu ly',
    question: 'Cong ty se lam gi sau cuoc goi?',
    options: ['Giao hang som hon', 'Gui bang bao gia moi', 'Kiem tra ton kho roi goi lai', 'Huy don hang'],
    answer: 'Kiem tra ton kho roi goi lai',
    explanation: 'Nhan vien chua xac nhan ngay duoc, can kiem tra ton kho va lien he lai trong chieu.',
    segments: [
      { speaker: 'Client', text: '来週火曜日の 納品を、できれば 月曜日に 早めて いただきたいのですが。' },
      { speaker: 'Staff', text: '在庫を 確認しないと すぐには お答えできません。' },
      { speaker: 'Client', text: '急ぎの 案件なので、今日の 午後までに ご連絡ください。' },
      { speaker: 'Staff', text: '承知しました。確認して 折り返します。' },
    ],
  },
  {
    id: 'n2-m2-business-trip',
    level: 'N2',
    mondai: 'Mondai 2',
    title: 'Sap xep lich cong tac',
    summary: 'Nghe nhieu rang buoc ve lich hop va di chuyen.',
    situation: 'Cap tren va nhan vien ban ve chuyen cong tac.',
    durationSec: 82,
    focus: 'Tong hop dieu kien, chon phuong an hop ly',
    question: 'Nhan vien se di Osaka khi nao?',
    options: ['Sang thu hai', 'Chieu thu hai', 'Toi thu hai', 'Sang thu ba'],
    answer: 'Toi thu hai',
    explanation: 'Vi sang thu hai phai hop noi bo, chieu gap khach o Tokyo, nen toi moi di tau.',
    segments: [
      { speaker: 'Manager', text: '月曜日の 朝は 社内会議、午後は 東京のお客様と 打ち合わせです。' },
      { speaker: 'Staff', text: 'では、大阪へは 夜の 新幹線で 移動して、火曜日の 朝から 訪問します。' },
      { speaker: 'Manager', text: 'その予定で 手配してください。' },
    ],
  },
  {
    id: 'n2-m3-system-alert',
    level: 'N2',
    mondai: 'Mondai 3',
    title: 'Thong bao loi he thong',
    summary: 'Nghe huong dan tam thoi khi he thong bi loi.',
    situation: 'Thong bao noi bo cong ty.',
    durationSec: 43,
    focus: 'Xu ly su co, hanh dong tam thoi',
    question: 'Nhan vien tam thoi phai nop bao cao bang cach nao?',
    options: ['Nhap lai vao he thong', 'Gui file qua email', 'In ra giay', 'Cho den ngay mai'],
    answer: 'Gui file qua email',
    explanation: 'Thong bao yeu cau gui file excel cho bo phan tong hop qua email.',
    segments: [
      { speaker: 'Announcer', text: '現在、売上管理システムに 障害が 発生して います。' },
      { speaker: 'Announcer', text: '本日分の 報告は エクセルファイルに まとめ、総務部へ メールで 送ってください。' },
    ],
  },
  {
    id: 'n2-m4-return-policy',
    level: 'N2',
    mondai: 'Mondai 4',
    title: 'Huong dan hoan tra san pham',
    summary: 'Nghe giai thich dieu kien doi tra hang.',
    situation: 'Nhan vien cham soc khach hang tu van.',
    durationSec: 79,
    focus: 'Dieu kien, giay to can thiet',
    question: 'Khach can chuan bi gi de doi hang?',
    options: ['Hoa don va hop san pham', 'The thanh vien', 'Anh chup san pham', 'Don xin doi hang'],
    answer: 'Hoa don va hop san pham',
    explanation: 'Nhan vien nhan manh can co hoa don va hop con day du phu kien.',
    segments: [
      { speaker: 'Staff', text: '交換をご希望の場合は、レシートと 商品の 箱を お持ちください。' },
      { speaker: 'Staff', text: '付属品が そろって いれば、購入から 一週間以内に 対応できます。' },
      { speaker: 'Client', text: 'わかりました。明日 店舗へ 持っていきます。' },
    ],
  },
  {
    id: 'n1-m1-strategy',
    level: 'N1',
    mondai: 'Mondai 1',
    title: 'Hop chien luoc quy moi',
    summary: 'Nghe lap luan ve uu tien dau tu trong quy toi.',
    situation: 'Hop cap quan ly.',
    durationSec: 95,
    focus: 'Lap luan, uu tien chien luoc',
    question: 'Nhom da uu tien phuong an nao?',
    options: ['Mo rong chi nhanh ngay', 'Tang ngan sach quang cao', 'Dau tu he thong ho tro khach hang', 'Cat giam nhan su'],
    answer: 'Dau tu he thong ho tro khach hang',
    explanation: 'Ho ket luan can cung co nen tang cham soc khach hang truoc khi mo rong.',
    segments: [
      { speaker: 'A', text: '新規出店を 急ぐより、まず 既存顧客の 満足度を 高める 仕組みづくりが 先決では ないでしょうか。' },
      { speaker: 'B', text: '確かに、問い合わせ対応の 遅れが 解約率に 影響している という データも 出ています。' },
      { speaker: 'A', text: 'であれば、次の 四半期は サポート体制の 強化に 重点を 置くべきです。' },
    ],
  },
  {
    id: 'n1-m2-radio',
    level: 'N1',
    mondai: 'Mondai 2',
    title: 'Phong van tren radio',
    summary: 'Nghe quan diem cua dien gia ve hoc suot doi.',
    situation: 'Chu de giao duc tren radio.',
    durationSec: 88,
    focus: 'Y chinh, thai do nguoi noi',
    question: 'Dien gia nhan manh dieu gi?',
    options: ['Hoc de thi dat chung chi', 'Hoc de theo kip cong nghe va xa hoi', 'Hoc la viec cua gioi tre', 'Hoc chi can tai truong'],
    answer: 'Hoc de theo kip cong nghe va xa hoi',
    explanation: 'Dien gia noi viec hoc lien tuc giup thich ung voi xa hoi thay doi nhanh.',
    segments: [
      { speaker: 'Host', text: '生涯学習が 注目される 理由を どう お考えですか。' },
      { speaker: 'Guest', text: '資格取得そのものより、変化の 激しい 社会に 合わせて 学び続ける 姿勢が 重要だからです。' },
      { speaker: 'Guest', text: '学ぶ場は 学校に 限らず、仕事や 地域活動の 中にも あります。' },
    ],
  },
  {
    id: 'n1-m3-policy',
    level: 'N1',
    mondai: 'Mondai 3',
    title: 'Thong bao chinh sach moi',
    summary: 'Nghe noi dung thay doi va doi tuong ap dung.',
    situation: 'Thong bao trong co quan.',
    durationSec: 56,
    focus: 'Pham vi ap dung, thoi diem hieu luc',
    question: 'Chinh sach moi ap dung cho ai tu thang sau?',
    options: ['Tat ca nhan vien', 'Nhan vien moi vao', 'Khoi van phong va kinh doanh', 'Nhan vien hop dong ngan han'],
    answer: 'Khoi van phong va kinh doanh',
    explanation: 'Thong bao neu ro giai doan dau ap dung cho hai khoi nay, sau do moi mo rong.',
    segments: [
      { speaker: 'Announcer', text: '来月から 新しい 在宅勤務制度を 導入します。まずは 本社の 事務部門と 営業部門を 対象とし、運用状況を 見てから 他部署へ 広げます。' },
    ],
  },
  {
    id: 'n1-m4-commentary',
    level: 'N1',
    mondai: 'Mondai 4',
    title: 'Binh luan chuyen de',
    summary: 'Nghe bai binh luan dai va xac dinh ket luan.',
    situation: 'Chuong trinh binh luan xa hoi.',
    durationSec: 102,
    focus: 'Tong hop y chinh, ket luan ham y',
    question: 'Ket luan cua nguoi noi la gi?',
    options: ['Can giam tat ca quy dinh', 'Cong nghe tu dong se giai quyet moi van de', 'Can can bang giua hieu qua va tinh ben vung', 'Nen tri hoan thay doi'],
    answer: 'Can can bang giua hieu qua va tinh ben vung',
    explanation: 'Nguoi noi khong phan doi doi moi, nhung nhan manh can xem tac dong dai han.',
    segments: [
      { speaker: 'Speaker', text: '効率化を 追い求める あまり、地域社会や 環境への 影響が 後回しに されては 本末転倒です。' },
      { speaker: 'Speaker', text: '今 求められているのは、短期的な 成果と 長期的な 持続可能性を どう 両立させるかという 視点でしょう。' },
      { speaker: 'Speaker', text: 'その意味で、選択肢を 単純な 二項対立で 捉えるべきでは ありません。' },
    ],
  },
];