export type ListeningLevel = 'N5' | 'N4' | 'N3' | 'N2' | 'N1';

export type ListeningMondai = 'Mondai 1' | 'Mondai 2' | 'Mondai 3' | 'Mondai 4';

export interface ListeningSegment {
  speaker: string;
  text: string;
}

export interface ListeningPractice {
  id: string;
  level: ListeningLevel;
  mondai: ListeningMondai;
  title: string;
  summary: string;
  situation: string;
  durationSec: number;
  focus: string;
  question: string;
  options: string[];
  answer: string;
  explanation: string;
  audioUrl?: string | null;
  segments: ListeningSegment[];
}

export const LISTENING_LEVEL_META: Record<ListeningLevel, { badgeBg: string; badgeText: string; accent: string; desc: string }> = {
  N5: { badgeBg: '#DCFCE7', badgeText: '#15803D', accent: '#4ADE80', desc: 'Cơ bản, hội thoại rất ngắn' },
  N4: { badgeBg: '#DBEAFE', badgeText: '#1D4ED8', accent: '#60A5FA', desc: 'Hội thoại thông dụng' },
  N3: { badgeBg: '#FEF9C3', badgeText: '#92400E', accent: '#FACC15', desc: 'Tình huống mở rộng' },
  N2: { badgeBg: '#FFEDD5', badgeText: '#C2410C', accent: '#FB923C', desc: 'Nghe công việc, thông báo' },
  N1: { badgeBg: '#FFE4E6', badgeText: '#BE123C', accent: '#FB7185', desc: 'Nội dung học thuật, phân tích' },
};

export const LISTENING_MONDAI_LABELS: Record<ListeningMondai, string> = {
  'Mondai 1': 'Chọn ý đúng trong hội thoại ngắn',
  'Mondai 2': 'Nhịp hỏi đáp và chọn hành động',
  'Mondai 3': 'Nghe thông báo và tìm thông tin',
  'Mondai 4': 'Nghe nội dung dài hơn và tổng hợp ý',
};

export const LISTENING_PRACTICES: ListeningPractice[] = [
  {
    id: 'n5-m1-combini',
    level: 'N5',
    mondai: 'Mondai 1',
    title: 'Mua đồ ăn ở combini',
    summary: 'Hội thoại ngắn về việc chọn món ăn trước giờ học.',
    situation: 'Bạn bè hẹn nhau mua đồ ăn ở cửa hàng tiện lợi.',
    durationSec: 36,
    focus: 'Giá tiền, lựa chọn đơn giản',
    question: 'Hai người sẽ mua gì?',
    options: ['Bánh mì và sữa', 'Onigiri và trà', 'Mì gói và nước', 'Bánh ngọt và cà phê'],
    answer: 'Onigiri và trà',
    explanation: 'Người nam nói sẽ lấy onigiri, người nữ nói lấy thêm một chai trà.',
    segments: [
      { speaker: 'A', text: 'もうすぐ 授業ですね。コンビニで 何か 買いましょうか。' },
      { speaker: 'B', text: 'そうですね。わたし、おにぎりを 一つ 買います。' },
      { speaker: 'A', text: 'じゃあ、ぼくは お茶を 二本 買います。' },
      { speaker: 'B', text: '一本で いいです。いっしょに 飲みましょう。' },
    ],
  },
  {
    id: 'n5-m2-station',
    level: 'N5',
    mondai: 'Mondai 2',
    title: 'Hẹn gặp ở nhà ga',
    summary: 'Nghe thời gian và địa điểm gặp mặt.',
    situation: 'Một người gọi điện thay đổi điểm hẹn.',
    durationSec: 41,
    focus: 'Giờ giấc, địa điểm',
    question: 'Hai người sẽ gặp nhau ở đâu?',
    options: ['Cửa Tây', 'Cửa Đông', 'Trước cửa hàng sách', 'Bên trạm xe buýt'],
    answer: 'Cửa Đông',
    explanation: 'Ban đầu hẹn ở cửa Tây nhưng sau đó đổi sang cửa Đông.',
    segments: [
      { speaker: 'A', text: 'もしもし、六時に 駅の 西口で 会いますね。' },
      { speaker: 'B', text: 'すみません、西口は 工事中です。東口に しても いいですか。' },
      { speaker: 'A', text: 'わかりました。じゃあ、東口の パン屋の 前で。' },
      { speaker: 'B', text: 'はい、六時に 行きます。' },
    ],
  },
  {
    id: 'n5-m3-train-delay',
    level: 'N5',
    mondai: 'Mondai 3',
    title: 'Thông báo tàu đến chậm',
    summary: 'Nghe thông báo ngắn tại nhà ga.',
    situation: 'Thông báo công cộng.',
    durationSec: 28,
    focus: 'Thông tin giao thông căn bản',
    question: 'Tàu đi Ueno đến chậm bao lâu?',
    options: ['5 phút', '10 phút', '15 phút', '20 phút'],
    answer: '10 phút',
    explanation: 'Thông báo nói tàu đến chậm mười phút do mưa lớn.',
    segments: [
      { speaker: 'Announcer', text: '上野行きの 電車は 大雨のため、十分ほど 遅れて います。' },
      { speaker: 'Announcer', text: 'ご利用の お客様は 三番線で お待ち ください。' },
    ],
  },
  {
    id: 'n4-m1-restaurant',
    level: 'N4',
    mondai: 'Mondai 1',
    title: 'Gọi món ở quán ăn',
    summary: 'Hội thoại về món chính và nước uống.',
    situation: 'Khách và nhân viên gọi món.',
    durationSec: 45,
    focus: 'Món ăn, thay đổi đơn gọi',
    question: 'Người phụ nữ cuối cùng gọi gì?',
    options: ['Cà ri và trà đá', 'Miso ramen và nước', 'Udon và trà nóng', 'Cơm cá và cà phê'],
    answer: 'Udon và trà nóng',
    explanation: 'Cô ấy đổi từ ramen sang udon và chọn trà nóng.',
    segments: [
      { speaker: 'Staff', text: 'ご注文は お決まりですか。' },
      { speaker: 'A', text: 'みそラーメンを お願いします。あ、やっぱり うどんに します。' },
      { speaker: 'Staff', text: '飲み物は いかがですか。' },
      { speaker: 'A', text: '冷たい水ではなくて、温かい お茶を ください。' },
    ],
  },
  {
    id: 'n4-m2-absence-call',
    level: 'N4',
    mondai: 'Mondai 2',
    title: 'Xin nghỉ buổi học',
    summary: 'Nghe lý do xin nghỉ và việc nộp bài.',
    situation: 'Sinh viên gọi cho giáo viên.',
    durationSec: 52,
    focus: 'Lý do, cách xử lý tiếp theo',
    question: 'Sinh viên phải làm gì?',
    options: ['Nộp bài hôm nay', 'Đến lớp chiều mai', 'Gửi bài bằng email', 'Gặp cô giáo ở văn phòng'],
    answer: 'Gửi bài bằng email',
    explanation: 'Cô giáo bảo sinh viên gửi bài tập qua email trước tối nay.',
    segments: [
      { speaker: 'A', text: '先生、熱が あるので、今日の 授業を 休みます。' },
      { speaker: 'B', text: 'わかりました。宿題は できましたか。' },
      { speaker: 'A', text: 'はい、もう できました。' },
      { speaker: 'B', text: 'では、今晩までに メールで 送って ください。' },
    ],
  },
  {
    id: 'n4-m3-room-change',
    level: 'N4',
    mondai: 'Mondai 3',
    title: 'Đổi phòng học',
    summary: 'Thông báo thay đổi phòng học trong trường.',
    situation: 'Thông báo tại hành lang trường.',
    durationSec: 31,
    focus: 'Số phòng, lý do thay đổi',
    question: 'Lớp chuyển sang phòng nào?',
    options: ['Phòng 201', 'Phòng 305', 'Phòng 501', 'Phòng 510'],
    answer: 'Phòng 305',
    explanation: 'Thông báo nói phòng 201 đang sửa máy chiếu nên lớp học ở phòng 305.',
    segments: [
      { speaker: 'Announcer', text: '二〇一教室の プロジェクターが 故障したため、三時からの 授業は 三〇五教室で 行います。' },
      { speaker: 'Announcer', text: 'お間違えの ないように お願いします。' },
    ],
  },
  {
    id: 'n3-m1-meeting',
    level: 'N3',
    mondai: 'Mondai 1',
    title: 'Sắp xếp họp nhóm',
    summary: 'Ba người thống nhất lịch họp cho dự án.',
    situation: 'Trao đổi trong câu lạc bộ.',
    durationSec: 66,
    focus: 'So sánh lựa chọn, tổng hợp lịch',
    question: 'Nhóm sẽ họp lúc nào?',
    options: ['Thứ sáu 6 giờ', 'Thứ bảy 10 giờ sáng', 'Chủ nhật 2 giờ chiều', 'Thứ bảy 2 giờ chiều'],
    answer: 'Thứ bảy 10 giờ sáng',
    explanation: 'Hai người không rảnh chiều thứ bảy và chủ nhật, nên chọn sáng thứ bảy.',
    segments: [
      { speaker: 'A', text: '今週、発表の 打ち合わせを したいですね。' },
      { speaker: 'B', text: '金曜日の 六時は アルバイトが あって 無理です。' },
      { speaker: 'C', text: '日曜日の 午後は 家族の 予定が あります。' },
      { speaker: 'A', text: 'じゃあ、土曜日の 午前十時なら どうですか。' },
      { speaker: 'B', text: 'それなら 大丈夫です。' },
      { speaker: 'C', text: 'わたしも 行けます。' },
    ],
  },
  {
    id: 'n3-m2-weekend-course',
    level: 'N3',
    mondai: 'Mondai 2',
    title: 'Chọn khóa học cuối tuần',
    summary: 'Nghe 2 lựa chọn khóa học và mục tiêu học tập.',
    situation: 'Bạn học viên hỏi tư vấn viên.',
    durationSec: 59,
    focus: 'Mục tiêu học tập, ưu tiên nội dung',
    question: 'Học viên nên chọn khóa nào?',
    options: ['Khóa viết email', 'Khóa thuyết trình', 'Khóa đọc tin tức', 'Khóa ngữ pháp nâng cao'],
    answer: 'Khóa thuyết trình',
    explanation: 'Học viên cần cải thiện kỹ năng nói trước lớp nên được khuyên khóa thuyết trình.',
    segments: [
      { speaker: 'A', text: '週末の コースを 取りたいんですが、仕事で 発表する ことが 多いんです。' },
      { speaker: 'B', text: 'それなら、メール作文より プレゼンテーションの クラスが いいですね。' },
      { speaker: 'A', text: '人前で 話すのが 苦手なので、ぜひ 参加したいです。' },
      { speaker: 'B', text: '土曜日の 午後に 初級クラスが ありますよ。' },
    ],
  },
  {
    id: 'n3-m3-hall-announcement',
    level: 'N3',
    mondai: 'Mondai 3',
    title: 'Thông báo tại hội trường',
    summary: 'Nghe hướng dẫn vào cửa và nhận tài liệu.',
    situation: 'Trước sự kiện công cộng.',
    durationSec: 37,
    focus: 'Thứ tự thao tác, địa điểm nhận tài liệu',
    question: 'Người tham dự phải làm gì trước khi vào hội trường?',
    options: ['Mua vé mới', 'Nhận tài liệu ở bàn số 2', 'Ký tên ở cửa sau', 'Gửi hành lý ở tầng 2'],
    answer: 'Nhận tài liệu ở bàn số 2',
    explanation: 'Thông báo yêu cầu nhận tài liệu ở bàn số 2 trước khi vào.',
    segments: [
      { speaker: 'Announcer', text: '講演会に 参加される 方は、会場に 入る 前に 二番カウンターで 資料を 受け取って ください。' },
      { speaker: 'Announcer', text: 'その後、前の ドアから お入りください。' },
    ],
  },
  {
    id: 'n3-m4-library',
    level: 'N3',
    mondai: 'Mondai 4',
    title: 'Thủ tục mượn sách thư viện',
    summary: 'Nghe hướng dẫn có nhiều bước.',
    situation: 'Nhân viên thư viện giải thích thủ tục mới.',
    durationSec: 71,
    focus: 'Nhớ thứ tự bước và điều kiện',
    question: 'Người nghe phải làm gì nếu chưa có thẻ thư viện?',
    options: ['Đăng ký online trước', 'Hỏi bàn tiếp đón', 'Đi chụp ảnh thẻ', 'Mua thẻ tạm thời'],
    answer: 'Hỏi bàn tiếp đón',
    explanation: 'Nhân viên nói nếu chưa có thẻ thì đến bàn tiếp đón để làm thủ tục.',
    segments: [
      { speaker: 'Staff', text: '本を 借りる 前に、学生証か 図書館カードを 機械に かざしてください。' },
      { speaker: 'Staff', text: 'カードを お持ちで ない 方は、先に 受付で 登録を してください。' },
      { speaker: 'Staff', text: '返却日は レシートに 書いて ありますので、確認を お願いします。' },
    ],
  },
  {
    id: 'n2-m1-client-call',
    level: 'N2',
    mondai: 'Mondai 1',
    title: 'Trao đổi với khách hàng',
    summary: 'Nghe yêu cầu điều chỉnh lịch giao hàng.',
    situation: 'Nhân viên công ty và khách hàng điện đàm.',
    durationSec: 74,
    focus: 'Thông tin công việc, ưu tiên xử lý',
    question: 'Công ty sẽ làm gì sau cuộc gọi?',
    options: ['Giao hàng sớm hơn', 'Gửi bảng báo giá mới', 'Kiểm tra tồn kho rồi gọi lại', 'Hủy đơn hàng'],
    answer: 'Kiểm tra tồn kho rồi gọi lại',
    explanation: 'Nhân viên chưa xác nhận ngay được, cần kiểm tra tồn kho và liên hệ lại trong chiều.',
    segments: [
      { speaker: 'Client', text: '来週火曜日の 納品を、できれば 月曜日に 早めて いただきたいのですが。' },
      { speaker: 'Staff', text: '在庫を 確認しないと すぐには お答えできません。' },
      { speaker: 'Client', text: '急ぎの 案件なので、今日の 午後までに ご連絡ください。' },
      { speaker: 'Staff', text: '承知しました。確認して 折り返します。' },
    ],
  },
  {
    id: 'n2-m2-business-trip',
    level: 'N2',
    mondai: 'Mondai 2',
    title: 'Sắp xếp lịch công tác',
    summary: 'Nghe nhiều ràng buộc về lịch họp và di chuyển.',
    situation: 'Cấp trên và nhân viên bàn về chuyến công tác.',
    durationSec: 82,
    focus: 'Tổng hợp điều kiện, chọn phương án hợp lý',
    question: 'Nhân viên sẽ đi Osaka khi nào?',
    options: ['Sáng thứ hai', 'Chiều thứ hai', 'Tối thứ hai', 'Sáng thứ ba'],
    answer: 'Tối thứ hai',
    explanation: 'Vì sáng thứ hai phải họp nội bộ, chiều gặp khách ở Tokyo, nên tối mới đi tàu.',
    segments: [
      { speaker: 'Manager', text: '月曜日の 朝は 社内会議、午後は 東京のお客様と 打ち合わせです。' },
      { speaker: 'Staff', text: 'では、大阪へは 夜の 新幹線で 移動して、火曜日の 朝から 訪問します。' },
      { speaker: 'Manager', text: 'その予定で 手配してください。' },
    ],
  },
  {
    id: 'n2-m3-system-alert',
    level: 'N2',
    mondai: 'Mondai 3',
    title: 'Thông báo lỗi hệ thống',
    summary: 'Nghe hướng dẫn tạm thời khi hệ thống bị lỗi.',
    situation: 'Thông báo nội bộ công ty.',
    durationSec: 43,
    focus: 'Xử lý sự cố, hành động tạm thời',
    question: 'Nhân viên tạm thời phải nộp báo cáo bằng cách nào?',
    options: ['Nhập lại vào hệ thống', 'Gửi file qua email', 'In ra giấy', 'Chờ đến ngày mai'],
    answer: 'Gửi file qua email',
    explanation: 'Thông báo yêu cầu gửi file Excel cho bộ phận tổng hợp qua email.',
    segments: [
      { speaker: 'Announcer', text: '現在、売上管理システムに 障害が 発生して います。' },
      { speaker: 'Announcer', text: '本日分の 報告は エクセルファイルに まとめ、総務部へ メールで 送ってください。' },
    ],
  },
  {
    id: 'n2-m4-return-policy',
    level: 'N2',
    mondai: 'Mondai 4',
    title: 'Hướng dẫn hoàn trả sản phẩm',
    summary: 'Nghe giải thích điều kiện đổi trả hàng.',
    situation: 'Nhân viên chăm sóc khách hàng tư vấn.',
    durationSec: 79,
    focus: 'Điều kiện, giấy tờ cần thiết',
    question: 'Khách cần chuẩn bị gì để đổi hàng?',
    options: ['Hóa đơn và hộp sản phẩm', 'Thẻ thành viên', 'Ảnh chụp sản phẩm', 'Đơn xin đổi hàng'],
    answer: 'Hóa đơn và hộp sản phẩm',
    explanation: 'Nhân viên nhấn mạnh cần có hóa đơn và hộp còn đầy đủ phụ kiện.',
    segments: [
      { speaker: 'Staff', text: '交換をご希望の場合は、レシートと 商品の 箱を お持ちください。' },
      { speaker: 'Staff', text: '付属品が そろって いれば、購入から 一週間以内に 対応できます。' },
      { speaker: 'Client', text: 'わかりました。明日 店舗へ 持っていきます。' },
    ],
  },
  {
    id: 'n1-m1-strategy',
    level: 'N1',
    mondai: 'Mondai 1',
    title: 'Họp chiến lược quý mới',
    summary: 'Nghe lập luận về ưu tiên đầu tư trong quý tới.',
    situation: 'Họp cấp quản lý.',
    durationSec: 95,
    focus: 'Lập luận, ưu tiên chiến lược',
    question: 'Nhóm đã ưu tiên phương án nào?',
    options: ['Mở rộng chi nhánh ngay', 'Tăng ngân sách quảng cáo', 'Đầu tư hệ thống hỗ trợ khách hàng', 'Cắt giảm nhân sự'],
    answer: 'Đầu tư hệ thống hỗ trợ khách hàng',
    explanation: 'Họ kết luận cần củng cố nền tảng chăm sóc khách hàng trước khi mở rộng.',
    segments: [
      { speaker: 'A', text: '新規出店を 急ぐより、まず 既存顧客の 満足度を 高める 仕組みづくりが 先決では ないでしょうか。' },
      { speaker: 'B', text: '確かに、問い合わせ対応の 遅れが 解約率に 影響している という データも 出ています。' },
      { speaker: 'A', text: 'であれば、次の 四半期は サポート体制の 強化に 重点を 置くべきです。' },
    ],
  },
  {
    id: 'n1-m2-radio',
    level: 'N1',
    mondai: 'Mondai 2',
    title: 'Phỏng vấn trên radio',
    summary: 'Nghe quan điểm của diễn giả về học suốt đời.',
    situation: 'Chủ đề giáo dục trên radio.',
    durationSec: 88,
    focus: 'Ý chính, thái độ người nói',
    question: 'Diễn giả nhấn mạnh điều gì?',
    options: ['Học để thi đạt chứng chỉ', 'Học để theo kịp công nghệ và xã hội', 'Học là việc của giới trẻ', 'Học chỉ cần tại trường'],
    answer: 'Học để theo kịp công nghệ và xã hội',
    explanation: 'Diễn giả nói việc học liên tục giúp thích ứng với xã hội thay đổi nhanh.',
    segments: [
      { speaker: 'Host', text: '生涯学習が 注目される 理由を どう お考えですか。' },
      { speaker: 'Guest', text: '資格取得そのものより、変化の 激しい 社会に 合わせて 学び続ける 姿勢が 重要だからです。' },
      { speaker: 'Guest', text: '学ぶ場は 学校に 限らず、仕事や 地域活動の 中にも あります。' },
    ],
  },
  {
    id: 'n1-m3-policy',
    level: 'N1',
    mondai: 'Mondai 3',
    title: 'Thông báo chính sách mới',
    summary: 'Nghe nội dung thay đổi và đối tượng áp dụng.',
    situation: 'Thông báo trong cơ quan.',
    durationSec: 56,
    focus: 'Phạm vi áp dụng, thời điểm hiệu lực',
    question: 'Chính sách mới áp dụng cho ai từ tháng sau?',
    options: ['Tất cả nhân viên', 'Nhân viên mới vào', 'Khối văn phòng và kinh doanh', 'Nhân viên hợp đồng ngắn hạn'],
    answer: 'Khối văn phòng và kinh doanh',
    explanation: 'Thông báo nêu rõ giai đoạn đầu áp dụng cho hai khối này, sau đó mới mở rộng.',
    segments: [
      { speaker: 'Announcer', text: '来月から 新しい 在宅勤務制度を 導入します。まずは 本社の 事務部門と 営業部門を 対象とし、運用状況を 見てから 他部署へ 広げます。' },
    ],
  },
  {
    id: 'n1-m4-commentary',
    level: 'N1',
    mondai: 'Mondai 4',
    title: 'Bình luận chuyên đề',
    summary: 'Nghe bài bình luận dài và xác định kết luận.',
    situation: 'Chương trình bình luận xã hội.',
    durationSec: 102,
    focus: 'Tổng hợp ý chính, kết luận hàm ý',
    question: 'Kết luận của người nói là gì?',
    options: ['Cần giảm tất cả quy định', 'Công nghệ tự động sẽ giải quyết mọi vấn đề', 'Cần cân bằng giữa hiệu quả và tính bền vững', 'Nên trì hoãn thay đổi'],
    answer: 'Cần cân bằng giữa hiệu quả và tính bền vững',
    explanation: 'Người nói không phản đối đổi mới, nhưng nhấn mạnh cần xem tác động dài hạn.',
    segments: [
      { speaker: 'Speaker', text: '効率化を 追い求める あまり、地域社会や 環境への 影響が 後回しに されては 本末転倒です。' },
      { speaker: 'Speaker', text: '今 求められているのは、短期的な 成果と 長期的な 持続可能性を どう 両立させるかという 視点でしょう。' },
      { speaker: 'Speaker', text: 'その意味で、選択肢を 単純な 二項対立で 捉えるべきでは ありません。' },
    ],
  },
];